### ISSUE TITLE
Cleanup SAs on broken relations rather than keys

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/charm-gcp-integrator#3]
See https://github.com/juju-solutions/charm-gcp-integrator/blob/master/lib/charms/layer/gcp.py#L213

The SAs are created per model / application pair, which is essentially per relation ID since there's no real use-case for multiple relations to the integrator.  So we should just cleanup the SA itself when the relation is broken which would cleanup the key as well.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809347.
